### ISSUE TITLE
Unresolved Layout files

### ISSUE THREAD

**Issue by smish-hash** [mocklets/pluto#247] opened 2023-07-12 07:29 UTC
**Describe the bug**
When using individual plugins, after adding the dependencies, I am not able to rebuild my application. It says there are 4 files in the layout folder which contributes to "unknown resource linking failed". There is no workaround for this.

This happens when using the bundle dependency as well, but the workaround is to go to the folder where the layout files are present and delete them. After that, I am able to implement Pluto as intended.

Tried on Pluto version 2.1.2, 2.1.3, 2.1.4

**To Reproduce**
Steps to reproduce the behaviour:
1. Add the individual network dependency
2. Click on sync now and then try to rebuild the project
3. See the error

**Expected behaviour**
The project should build successfully without showing any error

**Smartphone (please complete the following information):**
 - Device: Samsung S23 Ultra
 - OS: Android 13

**Comment by vvictor10** [comment] 2023-07-12 17:46
Running into the same issue on 2.1.3. Do we know of an older version which does not have this issue?

**Comment by vvictor10** [comment] 2023-07-12 20:15
Had to go back to 2.0.9 to get it work with the network plugin.

https://github.com/androidPluto/pluto/commits/develop/pluto-plugins/base/lib/src/main/res/layout/pluto___fragment_key_value_pair_edit.xml

This resource, as per the history, introduced on Mar 24, 2023 seems to have the issue.

**Comment by srtvprateek** [comment] 2023-07-13 05:41
@smish-hash can you share code snippet for how you are adding the dependencies & full error logs

**Comment by smish-hash** [comment] 2023-07-13 08:53
@srtvprateek 
In build.gradle (app level)

pluto_version = "2.1.3"

    `debugImplementation "com.plutolib:pluto:$pluto_version"
    releaseImplementation "com.plutolib:pluto-no-op:$pluto_version"

    debugImplementation "com.plutolib.plugins:bundle-core:$pluto_version"
    releaseImplementation "com.plutolib.plugins:bundle-core-no-op:$pluto_version"`


For some reason, I am not able to regenerate this error. I am not sure why.
But I am sharing the names of the files that were causing the issue. I hope that will help you. I will try to see if I can generate the error again.

- pluto___fragment_key_value_pair_edit.xml
- pluto___layout_content_share_options.xml
- pluto___fragment_share.xml
- pluto___view_key_value_pair.xml
- pluto___view_tabular_data.xml


Once I deleted these files, I was able to build my project

**Comment by srtvprateek** [comment] 2023-07-18 16:14
@vvictor10 is it still not working for you for version `2.1.4`?

**Comment by vvictor10** [comment] 2023-07-18 16:57
@srtvprateek Yes, its still not working. I had to go back to 2.0.9 to get it work.

**Comment by srtvprateek** [comment] 2023-07-20 07:00
is the issue similar for you too?
https://github.com/androidPluto/pluto/issues/247#issuecomment-1633835113

but if the issue was limited to the file mentioned [here](https://github.com/androidPluto/pluto/issues/247#issuecomment-1633148425), it should be fixed with https://github.com/androidPluto/pluto/pull/248

**Comment by vvictor10** [comment] 2023-07-20 14:16
Yes, the issue was with [fragment_key_value_pair_edit.xml](https://github.com/androidPluto/pluto/commits/develop/pluto-plugins/base/lib/src/main/res/layout/pluto___fragment_key_value_pair_edit.xml).

**Comment by srtvprateek** [comment] 2023-07-21 05:48
@vvictor10 can you check if the issue is still there in `2.1.5`

**Comment by vvictor10** [comment] 2023-07-25 14:40
@srtvprateek 2.1.5 fixed the issue. Thanks for the quick resolution.

**Closed as completed** 2023-07-25 18:17 UTC
Labels: bug
